[tool.poetry]
name = "init-problem"
version = "0.1.1"
description = "Added path_parent as environment variable.
authors = ["vaibhavblayer <vaibhavblayer@gmail.com>"]
readme = "README.md"
packages = [{include = "init_problem"}]


[tool.poetry.scripts]
init-problem = "init_problem.main:main"


[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
